name: AWS Deploy

on: 
  pull_request:
  push:
    branches: 
      - master

jobs:
  build:
    name: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
 
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
  deploy_to_aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@master
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: aws access key id
        AWS_SECRET_ACCESS_KEY: aws secret key 
