name: COKI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
 
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run:
        npm i
        npm run build --if-present
        npm test
      env:
        CI: true
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: deploy to severless
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
